"""
Cross-language model compatibility test.

This test ensures that models saved in Python can be loaded in R and vice versa,
and that both languages produce identical predictions for the same model.
"""

import numpy as np
import json
import os
from gbrs import GBRS, save_model, load_model, save_predictions, load_predictions

DATA_DIR = os.path.join("tests", "data")
os.makedirs(DATA_DIR, exist_ok=True)


def test_cross_language_predictions():
    """
    Test that Python and R produce identical predictions.

    This test:
    1. Fits a model in Python on mtcars data
    2. Saves predictions from Python
    3. Compares with R predictions (to be generated by R script)
    """
    print("=" * 60)
    print("Cross-Language Prediction Comparison Test")
    print("=" * 60)

    # Load mtcars data (simplified version for testing)
    # In practice, this would be loaded from a shared CSV file
    print("\n1. Creating test dataset...")
    np.random.seed(42)
    X = np.random.randn(32, 2)  # Simulating mtcars with 2 features
    y = 20 + 3 * X[:, 0] - 2 * X[:, 1] + np.random.randn(32) * 2

    print(f"   Dataset: {X.shape[0]} samples, {X.shape[1]} features")

    # Fit model in Python
    print("\n2. Fitting model in Python...")
    model = GBRS(n_iter=10, lr=0.1, n_quantiles=5)
    model.fit(X, y)
    print("   ✓ Model fitted")

    # Save model
    print("\n3. Saving Python model...")
    save_model(
        model._model,
        os.path.join(DATA_DIR, "model_python_for_r.json"),
        objective="continuous",
        formula="y ~ x1 + x2",
    )
    print("   ✓ Model saved to model_python_for_r.json")

    # Make and save predictions
    print("\n4. Generating Python predictions...")
    predictions_py = model.predict(X)
    save_predictions(
        predictions_py, os.path.join(DATA_DIR, "predictions_python_test.json")
    )
    print(f"   ✓ Predictions saved: {len(predictions_py)} values")
    print(f"   Mean prediction: {np.mean(predictions_py):.4f}")
    print(f"   Std prediction: {np.std(predictions_py):.4f}")

    # Save test data for R to use
    print("\n5. Saving test data for R...")
    test_data = {"X": X.tolist(), "y": y.tolist()}
    with open(os.path.join(DATA_DIR, "test_data.json"), "w") as f:
        json.dump(test_data, f, indent=2)
    print("   ✓ Test data saved to test_data.json")

    print("\n" + "=" * 60)
    print("Python part complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Run the R script to generate R predictions")
    print("2. Compare predictions_python_test.json with predictions_r_test.json")
    print("3. They should be identical (within floating point tolerance)")

    return predictions_py


if __name__ == "__main__":
    test_cross_language_predictions()
