# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_proba <- function(x, y, n_iter, lr, n_quantiles, batch_size) {
    .Call('_gbrs_fit_proba', PACKAGE = 'gbrs', x, y, n_iter, lr, n_quantiles, batch_size)
}

fit <- function(x, y, n_iter, lr, n_quantiles, batch_size) {
    .Call('_gbrs_fit', PACKAGE = 'gbrs', x, y, n_iter, lr, n_quantiles, batch_size)
}

fit_survival <- function(x, time, event, n_iter, lr, n_quantiles, batch_size, quantiles) {
    .Call('_gbrs_fit_survival', PACKAGE = 'gbrs', x, time, event, n_iter, lr, n_quantiles, batch_size, quantiles)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_gbrs_RcppExport_registerCCallable', PACKAGE = 'gbrs')
})
